version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    links:
      - db